from __future__ import annotations

import json
from asyncio import Lock
from asyncio import timeout as asyncio_timeout
from contextlib import asynccontextmanager, suppress
from typing import TYPE_CHECKING, Self, cast, override

from asyncpg import Connection, InterfaceError, PostgresError
from asyncpg import connect as asyncpg_connect

# The engine's building blocks come from their own modules, not from the package:
# forbql.engines imports this subpackage through connect(), which would be a cycle.
from forbql.engines._errors import ErrorClass, QueryError
from forbql.engines._privileges import PrivilegeReport
from forbql.engines._protocol import QueryEngine, Restriction
from forbql.engines._result import Collector, ResultSet
from forbql.firewall import SchemaSnapshot
from forbql.policy import Engine, Limits

from ._privileges import ATTRIBUTES, REFUSALS, WARNINGS

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Awaitable, Callable

_PREFETCH_LIMIT = 200
"""Prefetch limit for PostgreSQL."""

_GRACE_SECONDS = 1.0
"""Grace period before prefetching again for PostgreSQL."""


_SNAPSHOT_SQL = """
SELECT table_schema, table_name, column_name
FROM information_schema.columns
WHERE table_schema NOT IN ('pg_catalog', 'information_schema')
ORDER BY table_schema, table_name, ordinal_position
"""
"""SQL to get the schema snapshot for PostgreSQL."""

_VIEWS_SQL = """
SELECT n.nspname AS table_schema, c.relname AS table_name,
       pg_get_viewdef(c.oid) AS definition
FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE c.relkind = 'v' AND n.nspname NOT IN ('pg_catalog', 'information_schema')
"""
"""SQL to read view definitions, which the firewall checks at startup."""

_SETTINGS = """
SELECT set_config('statement_timeout', $1, true),
       set_config('lock_timeout', $1, true),
       set_config('search_path', $2, true)
"""
"""SQL to set the settings for PostgreSQL."""

_LOST = (InterfaceError, OSError)
"""Failures of the connection itself rather than of the query."""


class PostgresEngine(QueryEngine):
    """A connection whose every query runs in a read-only transaction, then rolls back.

    Args:
        connection: asyncpg.Connection - Opened by `connect`.

    """

    _connection: Connection
    _lock: Lock
    """One operation at a time: asyncpg refuses a second one on the connection."""
    _search_path: str = "pg_catalog"
    """The search path for the PostgreSQL database."""

    def __init__(self, connection: Connection) -> None:
        self._connection = connection
        self._lock = Lock()
        self._search_path = "pg_catalog"

    @property
    @override
    def engine(self) -> Engine:
        """The engine name.

        Returns:
            Engine.POSTGRES - The engine name.

        """
        return Engine.POSTGRES

    @classmethod
    async def connect(cls, dsn: str) -> Self:
        """Open a connection.

        Args:
            dsn: str - A `postgresql://` URL or key=value string.

        Returns:
            Self - The engine.

        Raises:
            QueryError: If the server is unreachable or refuses the login.

        """
        try:
            connection = await asyncpg_connect(dsn)
        except (OSError, PostgresError) as error:
            raise QueryError(ErrorClass.CONNECTION, str(error)) from error
        return cls(connection)

    @override
    async def execute(self, sql: str, limits: Limits) -> ResultSet:
        """Run one query in a read-only transaction and roll it back.

        Args:
            sql: str - SQL regenerated by the firewall.
            limits: Limits - Time, row and byte bounds.

        Returns:
            ResultSet - The capped rows.

        """
        async with self._guarded():
            return await self._in_transaction(self._stream, sql, limits)

    @override
    async def estimate(self, sql: str, limits: Limits) -> float:
        """Ask the planner what the query would cost, without running it.

        Args:
            sql: str - SQL regenerated by the firewall.
            limits: Limits - Bounds; the time limit covers planning too.

        Returns:
            float - The plan's total cost, in the planner's units.

        """
        async with self._guarded():
            return await self._in_transaction(self._explain, sql, limits)

    @override
    async def snapshot(self) -> SchemaSnapshot:
        """Get the schema snapshot.

        Returns:
            SchemaSnapshot - The schema snapshot.

        """
        async with self._guarded():
            snapshot_records = await self._connection.fetch(_SNAPSHOT_SQL)
            view_records = await self._connection.fetch(_VIEWS_SQL)
            current = cast(
                "str",
                await self._connection.fetchval("SELECT current_schema()"),
            )

        tables: dict[str, list[str]] = {}
        for record in snapshot_records:
            key = f"{record['table_schema']}.{record['table_name']}"
            tables.setdefault(key, []).append(str(cast("str", record["column_name"])))

        definitions = {
            f"{record['table_schema']}.{record['table_name']}": str(
                cast("str", record["definition"]),
            )
            for record in view_records
        }
        default_schema = str(current)
        schemas = sorted({key.split(".")[0] for key in tables})
        self._search_path = ", ".join(["pg_catalog", *map(self._quote, schemas)])
        return SchemaSnapshot(
            default_schema=default_schema,
            tables={key: tuple(names) for key, names in tables.items()},
            # Views the role cannot read have no columns in the snapshot.
            views={key: sql for key, sql in definitions.items() if key in tables},
        )

    @override
    async def check_privileges(self) -> PrivilegeReport:
        """Find what the role may do beyond reading.

        Returns:
            PrivilegeReport - Refusals and warnings; a superuser gets one refusal.

        """
        async with self._guarded(), self._connection.transaction(readonly=True):
            _ = await self._connection.execute("SET LOCAL search_path = pg_catalog")
            return await self._privilege_report()

    @override
    async def restrict(self, _restriction: Restriction, /) -> None:
        """Nothing to do: the database role enforces what it may read."""

    @override
    async def close(self) -> None:
        """Close the connection."""
        async with self._lock:
            await self._connection.close()

    @asynccontextmanager
    async def _guarded(self) -> AsyncGenerator[None]:
        """Hold the connection, and turn driver failures into query errors.

        Yields:
            None - While the caller uses the connection.

        Raises:
            QueryError: If the database refuses or fails, or time runs out.

        """
        async with self._lock:
            try:
                yield
            except PostgresError as error:
                raise QueryError(*self._classify_error(error)) from error
            except TimeoutError as error:
                raise QueryError(ErrorClass.TIMEOUT, str(error)) from error
            except _LOST as error:
                raise QueryError(ErrorClass.CONNECTION, str(error)) from error

    async def _privilege_report(self) -> PrivilegeReport:
        """Ask the check's questions inside the caller's transaction.

        Returns:
            PrivilegeReport - Refusals and warnings.

        """
        attributes = await self._findings((ATTRIBUTES,))
        if "the role has SUPERUSER" in attributes:
            return PrivilegeReport(refusals=("the role has SUPERUSER",))
        return PrivilegeReport(
            refusals=attributes + await self._findings(REFUSALS),
            warnings=await self._findings(WARNINGS),
        )

    async def _findings(self, queries: tuple[str, ...]) -> tuple[str, ...]:
        """Run queries that return one text column; each row is one finding.

        Args:
            queries: tuple[str, ...] - The queries.

        Returns:
            tuple[str, ...] - The findings, in query order.

        """
        found: list[str] = []
        for query in queries:
            records = await self._connection.fetch(query)
            found.extend(str(cast("str", record[0])) for record in records)
        return tuple(found)

    async def _in_transaction[T](
        self,
        work: Callable[[str, Limits], Awaitable[T]],
        sql: str,
        limits: Limits,
    ) -> T:
        """Do the work inside a read-only transaction with the limits, then roll back.

        Args:
            work: Callable[[str, Limits], Awaitable[T]] - Streams or explains the query.
            sql: str - SQL regenerated by the firewall.
            limits: Limits - Time, row and byte bounds.

        Returns:
            T - What the work returned.

        """
        transaction = self._connection.transaction(readonly=True)
        await transaction.start()
        try:
            timeout = str(limits.statement_timeout_ms)
            _ = await self._connection.execute(_SETTINGS, timeout, self._search_path)
            return await work(sql, limits)
        finally:
            # A lost connection must not hide the error that lost it.
            with suppress(PostgresError, *_LOST):
                await transaction.rollback()

    async def _stream(self, sql: str, limits: Limits) -> ResultSet:
        """Stream the results of a query.

        Args:
            sql: str - SQL regenerated by the firewall.
            limits: Limits - Time, row and byte bounds.

        Returns:
            ResultSet - The capped rows.
        """
        collector = Collector(limits)
        async with asyncio_timeout(limits.statement_timeout_ms / 1000 + _GRACE_SECONDS):
            statement = await self._connection.prepare(sql)
            columns = [attr.name for attr in statement.get_attributes()]
            async for record in statement.cursor(prefetch=_PREFETCH_LIMIT):
                if not collector.add(tuple(record.values())):
                    break

        return collector.result(columns)

    async def _explain(self, sql: str, _limits: Limits) -> float:
        """Read the total cost of the query's plan.

        Args:
            sql: str - SQL regenerated by the firewall.
            _limits: Limits - Unused; the transaction already applies them.

        Returns:
            float - The plan's total cost.

        """
        plan = cast(
            "str",
            await self._connection.fetchval(f"EXPLAIN (FORMAT JSON) {sql}"),
        )
        return float(json.loads(plan)[0]["Plan"]["Total Cost"])  # pyright: ignore[reportAny]

    @classmethod
    def _quote(cls, name: str) -> str:
        return '"' + name.replace('"', '""') + '"'

    @classmethod
    def _classify_error(cls, error: PostgresError) -> tuple[ErrorClass, str]:
        state = str(getattr(error, "sqlstate", "") or "")
        text = str(error)
        if state == "57014":
            return ErrorClass.TIMEOUT, text
        if state == "42501":
            return ErrorClass.PERMISSION_DENIED, text
        if state == "25006":
            return ErrorClass.READ_ONLY, text
        if state.startswith(("42", "22")):
            return ErrorClass.INVALID_QUERY, text
        if state.startswith("08"):
            return ErrorClass.CONNECTION, text
        return ErrorClass.DATABASE, text
