from __future__ import annotations

from asyncio import Lock
from asyncio import timeout as asyncio_timeout
from contextlib import suppress
from typing import Self, cast, override

from asyncpg import Connection, InterfaceError, PostgresError
from asyncpg import connect as asyncpg_connect

# The engine's building blocks come from their own modules, not from the package:
# forbql.engines imports this subpackage through connect(), which would be a cycle.
from forbql.engines._errors import ErrorClass, QueryError
from forbql.engines._protocol import QueryEngine, Restriction
from forbql.engines._result import Collector, ResultSet
from forbql.firewall import SchemaSnapshot
from forbql.policy import Engine, Limits

_PREFETCH_LIMIT = 200
"""Prefetch limit for PostgreSQL."""

_GRACE_SECONDS = 1.0
"""Grace period before prefetching again for PostgreSQL."""


_SNAPSHOT_SQL = """
SELECT table_schema, table_name, column_name
FROM information_schema.columns
WHERE table_schema NOT IN ('pg_catalog', 'information_schema')
ORDER BY table_schema, table_name, ordinal_position
"""
"""SQL to get the schema snapshot for PostgreSQL."""

_SETTINGS = """
SELECT set_config('statement_timeout', $1, true),
       set_config('lock_timeout', $1, true),
       set_config('search_path', $2, true)
"""
"""SQL to set the settings for PostgreSQL."""

_LOST = (InterfaceError, OSError)
"""Failures of the connection itself rather than of the query."""


class PostgresEngine(QueryEngine):
    """A connection whose every query runs in a read-only transaction, then rolls back.

    Args:
        connection: asyncpg.Connection - Opened by `connect`.

    """

    _connection: Connection
    _lock: Lock
    """One operation at a time: asyncpg refuses a second one on the connection."""
    _search_path: str = "pg_catalog"
    """The search path for the PostgreSQL database."""

    def __init__(self, connection: Connection) -> None:
        self._connection = connection
        self._lock = Lock()
        self._search_path = "pg_catalog"

    @property
    @override
    def engine(self) -> Engine:
        """The engine name.

        Returns:
            Engine.POSTGRES - The engine name.

        """
        return Engine.POSTGRES

    @classmethod
    async def connect(cls, dsn: str) -> Self:
        """Open a connection.

        Args:
            dsn: str - A `postgresql://` URL or key=value string.

        Returns:
            Self - The engine.

        Raises:
            QueryError: If the server is unreachable or refuses the login.

        """
        try:
            connection = await asyncpg_connect(dsn)
        except (OSError, PostgresError) as error:
            raise QueryError(ErrorClass.CONNECTION, str(error)) from error
        return cls(connection)

    @override
    async def execute(self, sql: str, limits: Limits) -> ResultSet:
        """Run one query in a read-only transaction and roll it back.

        Args:
            sql: str - SQL regenerated by the firewall.
            limits: Limits - Time, row and byte bounds.

        Returns:
            ResultSet - The capped rows.

        Raises:
            QueryError: If the database refuses or fails the query, or time runs out.

        """
        async with self._lock:
            try:
                return await self._in_transaction(sql, limits)
            except PostgresError as error:
                raise QueryError(*self._classify_error(error)) from error
            except TimeoutError as error:
                raise QueryError(ErrorClass.TIMEOUT, str(error)) from error
            except _LOST as error:
                raise QueryError(ErrorClass.CONNECTION, str(error)) from error

    @override
    async def snapshot(self) -> SchemaSnapshot:
        """Get the schema snapshot.

        Returns:
            SchemaSnapshot - The schema snapshot.

        Raises:
            QueryError: If the database fails the reads.

        """
        try:
            async with self._lock:
                snapshot_records = await self._connection.fetch(_SNAPSHOT_SQL)
                current = cast(
                    "str",
                    await self._connection.fetchval("SELECT current_schema()"),
                )
        except PostgresError as error:
            raise QueryError(*self._classify_error(error)) from error
        except _LOST as error:
            raise QueryError(ErrorClass.CONNECTION, str(error)) from error

        tables: dict[str, list[str]] = {}
        for record in snapshot_records:
            key = f"{record['table_schema']}.{record['table_name']}"
            tables.setdefault(key, []).append(str(cast("str", record["column_name"])))

        default_schema = str(current)
        schemas = sorted({key.split(".")[0] for key in tables})
        self._search_path = ", ".join(["pg_catalog", *map(self._quote, schemas)])
        return SchemaSnapshot(
            default_schema=default_schema,
            tables={key: tuple(names) for key, names in tables.items()},
        )

    @override
    async def restrict(self, _restriction: Restriction, /) -> None:
        """Nothing to do: the database role enforces what it may read."""

    @override
    async def close(self) -> None:
        """Close the connection."""
        async with self._lock:
            await self._connection.close()

    async def _in_transaction(self, sql: str, limits: Limits) -> ResultSet:
        """Stream the query inside a read-only transaction, then roll it back.

        Args:
            sql: str - SQL regenerated by the firewall.
            limits: Limits - Time, row and byte bounds.

        Returns:
            ResultSet - The capped rows.

        """
        transaction = self._connection.transaction(readonly=True)
        await transaction.start()
        try:
            return await self._stream(sql, limits)
        finally:
            # A lost connection must not hide the error that lost it.
            with suppress(PostgresError, *_LOST):
                await transaction.rollback()

    async def _stream(self, sql: str, limits: Limits) -> ResultSet:
        """Stream the results of a query.

        Args:
            sql: str - SQL regenerated by the firewall.
            limits: Limits - Time, row and byte bounds.

        Returns:
            ResultSet - The capped rows.
        """
        timeout = str(limits.statement_timeout_ms)
        _ = await self._connection.execute(_SETTINGS, timeout, self._search_path)
        collector = Collector(limits)
        async with asyncio_timeout(limits.statement_timeout_ms / 1000 + _GRACE_SECONDS):
            statement = await self._connection.prepare(sql)
            columns = [attr.name for attr in statement.get_attributes()]
            async for record in statement.cursor(prefetch=_PREFETCH_LIMIT):
                if not collector.add(tuple(record.values())):
                    break

        return collector.result(columns)

    @classmethod
    def _quote(cls, name: str) -> str:
        return '"' + name.replace('"', '""') + '"'

    @classmethod
    def _classify_error(cls, error: PostgresError) -> tuple[ErrorClass, str]:
        state = str(getattr(error, "sqlstate", "") or "")
        text = str(error)
        if state == "57014":
            return ErrorClass.TIMEOUT, text
        if state == "42501":
            return ErrorClass.PERMISSION_DENIED, text
        if state == "25006":
            return ErrorClass.READ_ONLY, text
        if state.startswith(("42", "22")):
            return ErrorClass.INVALID_QUERY, text
        if state.startswith("08"):
            return ErrorClass.CONNECTION, text
        return ErrorClass.DATABASE, text
