from __future__ import annotations

import json
from asyncio import Lock, to_thread
from contextlib import suppress
from ssl import CERT_NONE, CERT_REQUIRED, VERIFY_X509_STRICT, create_default_context
from typing import TYPE_CHECKING, Self, cast, override
from urllib.parse import parse_qsl, unquote, urlsplit

from pymysql import connect as pymysql_connect
from pymysql.cursors import SSCursor
from pymysql.err import InterfaceError, MySQLError

# The engine's building blocks come from their own modules, not from the package:
# forbql.engines imports this subpackage through connect(), which would be a cycle.
from forbql.engines._errors import ErrorClass, QueryError
from forbql.engines._protocol import QueryEngine, Restriction
from forbql.engines._result import Collector, ResultSet
from forbql.engines._thread import run_locked
from forbql.firewall import SchemaSnapshot
from forbql.policy import Engine, Limits

from ._grants import read_grants
from ._plan import plan_cost

if TYPE_CHECKING:
    from ssl import SSLContext

    from pymysql.connections import Connection
    from pymysql.cursors import Cursor

    from forbql.engines._privileges import PrivilegeReport

_FETCHMANY_LIMIT = 200
"""Prefetch limit for MySQL."""


_SQL_MODE = (
    "ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,"
    "ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
)
"""SQL mode for MySQL.


sqlglot's MySQL dialect reads '...' as strings and `...` as identifiers, with
backslash escapes: the session must agree, or checked SQL means something else.
"""

_READ_ONLY = "SET SESSION transaction_read_only = ON"
"""SQL to set the session to read-only.

A read-only transaction alone does not stop DDL: MySQL commits before DDL, ending
the transaction. The session-wide read-only mode refuses DDL too.
"""


_SNAPSHOT = """
SELECT table_schema, table_name, column_name
FROM information_schema.columns
WHERE table_schema = DATABASE()
ORDER BY table_name, ordinal_position
"""
"""SQL to get the schema snapshot for MySQL."""

_VIEWS = """
SELECT table_schema, table_name, view_definition
FROM information_schema.views
WHERE table_schema = DATABASE()
"""
"""SQL to read view definitions; MySQL shows them only to holders of SHOW VIEW."""


_TIMEOUT = {1028, 1317, 3024}
"""Error codes for timeouts."""

_PERMISSION = {1044, 1045, 1142, 1143, 1227}
"""Error codes for permissions."""

_READ_ONLY_ERRORS = {1290, 1792}
"""Error codes for read-only errors."""

_INVALID = {1054, 1064, 1146, 1305, 1582}
"""Error codes for invalid errors."""

_CONNECTION = {2003, 2006, 2013}
"""Error codes for MySQL."""

_TLS_PARAMETERS = frozenset({"ssl-mode", "ssl-ca", "ssl-cert", "ssl-key"})
"""DSN query parameters the engine understands, named as the mysql client names them."""


type Row = tuple[object, ...]
"""A row of data from MySQL."""


class MySQLEngine(QueryEngine):
    """A connection in session read-only mode whose every query is rolled back.

    Args:
        connection: pymysql.Connection - Opened by `connect`.

    """

    _connection: Connection
    _lock: Lock
    """
    A lock to serialize access to the connection.
    One connection, used from worker threads one call at a time.
    """

    def __init__(self, connection: Connection) -> None:
        self._connection = connection
        self._lock = Lock()

    @property
    @override
    def engine(self) -> Engine:
        """The engine of the connection."""
        return Engine.MYSQL

    @classmethod
    async def connect(cls, dsn: str) -> Self:
        """Open a connection with the sql_mode the firewall assumes.

        Args:
            dsn: str - `mysql://user:password@host:port/database`.

        Returns:
            Self - The engine.

        """
        return cls(await to_thread(cls._open_connection, dsn))

    @override
    async def execute(self, sql: str, limits: Limits) -> ResultSet:
        """Run one query in a read-only transaction and roll it back.

        Args:
            sql: Query regenerated by Firewall.
            limits: Limits - Time, row and byte bounds.

        Returns:
            ResultSet - The capped rows.

        """
        return await run_locked(
            self._lock,
            self._collect_resultset,
            self._connection,
            sql,
            limits,
        )

    @override
    async def estimate(self, sql: str, limits: Limits) -> float | None:
        """Ask the optimizer what the query would cost, without running it.

        Args:
            sql: str - SQL regenerated by the firewall.
            limits: Limits - Bounds; the time limit covers planning too.

        Returns:
            float | None - The plan's cost; None if the plan carries none.

        """
        return await run_locked(
            self._lock,
            self._explain,
            self._connection,
            sql,
            limits,
        )

    @override
    async def snapshot(self) -> SchemaSnapshot:
        """Read the columns of the current database the account may use.

        Returns:
            SchemaSnapshot - The schema; the default schema is the current database.

        """
        rows, views, default_schema = await run_locked(
            self._lock,
            self._fetch_tables,
            self._connection,
        )

        tables: dict[str, list[str]] = {}
        for schema, table, col in rows:
            tables.setdefault(f"{schema}.{table}", []).append(str(col))

        # An empty definition means the account lacks SHOW VIEW: it cannot be checked.
        definitions = {
            f"{schema}.{view}": str(definition) or None
            for schema, view, definition in views
        }
        return SchemaSnapshot(
            default_schema=default_schema,
            tables={key: tuple(names) for key, names in tables.items()},
            views={key: sql for key, sql in definitions.items() if key in tables},
        )

    @override
    async def check_privileges(self) -> PrivilegeReport:
        """Find what the account may do beyond reading, from `SHOW GRANTS`.

        Returns:
            PrivilegeReport - Refusals and warnings.

        """
        grants, database = await run_locked(
            self._lock,
            self._fetch_grants,
            self._connection,
        )
        return read_grants(grants, database)

    @override
    async def restrict(self, restriction: Restriction, /) -> None:
        """Nothing to do: the account's grants enforce what it may read."""

    @override
    async def close(self) -> None:
        """Close the connection."""
        await run_locked(self._lock, self._connection.close)

    @classmethod
    def _fetch_tables(
        cls,
        connection: Connection[Cursor],
    ) -> tuple[list[Row], list[Row], str]:
        """Fetch the columns and view definitions of the current database.

        Args:
            connection: pymysql.Connection[pymysql.cursors.Cursor] - The connection.

        Returns:
            tuple[list[Row], list[Row], str] - The columns, the views and the current
                database.

        Raises:
            QueryError: If the database fails the reads.

        """
        try:
            with connection.cursor() as cursor:
                rows = cls._rows(cursor, _SNAPSHOT)
                views = cls._rows(cursor, _VIEWS)
                database = cls._rows(cursor, "SELECT DATABASE()")[0][0]
        except MySQLError as error:
            raise QueryError(*cls._classify_error(error)) from error
        finally:
            cls._rollback(connection)
        return rows, views, str(database)

    @classmethod
    def _fetch_grants(cls, connection: Connection[Cursor]) -> tuple[list[str], str]:
        """Fetch the account's grants and the current database.

        Args:
            connection: pymysql.Connection[pymysql.cursors.Cursor] - The connection.

        Returns:
            tuple[list[str], str] - One `GRANT` statement per line, and the database.

        Raises:
            QueryError: If the database fails the reads.

        """
        try:
            with connection.cursor() as cursor:
                grants = cls._rows(cursor, "SHOW GRANTS")
                database = cls._rows(cursor, "SELECT DATABASE()")[0][0]
        except MySQLError as error:
            raise QueryError(*cls._classify_error(error)) from error
        finally:
            cls._rollback(connection)
        return [str(row[0]) for row in grants], str(database)

    @classmethod
    def _rows(cls, cursor: Cursor, sql: str) -> list[Row]:
        """Run a query and fetch all its rows.

        Args:
            cursor: pymysql.cursors.Cursor - The cursor.
            sql: str - The query.

        Returns:
            list[Row] - The rows.

        """
        _ = cursor.execute(sql)
        return cast("list[Row]", list(cursor.fetchall()))

    @classmethod
    def _open_connection(cls, dsn: str) -> Connection[Cursor]:
        """Open a connection with the sql_mode the firewall assumes.

        Args:
            dsn: str - `mysql://user:password@host:port/database`.

        Returns:
            pymysql.Connection[pymysql.cursors.Cursor] - The connection.

        Raises:
            QueryError: If the connection fails.

        """
        url = urlsplit(dsn)
        tls, tls_disabled = cls._tls(url.query)
        try:
            return pymysql_connect(
                host=url.hostname or "127.0.0.1",
                port=url.port or 3306,
                user=unquote(url.username or ""),
                password=unquote(url.password or ""),
                database=url.path.lstrip("/") or None,
                charset="utf8mb4",
                autocommit=False,
                init_command=f"SET SESSION sql_mode = '{_SQL_MODE}'",
                ssl=tls,
                ssl_disabled=tls_disabled,
            )
        except MySQLError as error:
            raise QueryError(ErrorClass.CONNECTION, str(error)) from error

    @classmethod
    def _tls(cls, query: str) -> tuple[SSLContext | None, bool]:
        """Read the DSN's TLS parameters the way the mysql client reads them.

        `PREFERRED`, the default, tries TLS and falls back to plain text; `REQUIRED`
        refuses plain text; the `VERIFY_*` modes also check the certificate.

        Args:
            query: str - The query string of the DSN.

        Returns:
            tuple[SSLContext | None, bool] - The TLS context when TLS is required,
                and whether TLS is disabled.

        Raises:
            ValueError: If a parameter is unknown or its value is not a mode.

        """
        parameters = dict(parse_qsl(query, keep_blank_values=True))
        if unknown := sorted(parameters.keys() - _TLS_PARAMETERS):
            msg = f"unsupported MySQL DSN parameters: {', '.join(unknown)}"
            raise ValueError(msg)

        mode = parameters.get("ssl-mode", "PREFERRED").upper()
        if mode in {"PREFERRED", "DISABLED"}:
            if parameters.keys() - {"ssl-mode"}:
                msg = f"ssl-ca, ssl-cert and ssl-key need an ssl-mode above {mode}"
                raise ValueError(msg)
            return None, mode == "DISABLED"
        if mode not in {"REQUIRED", "VERIFY_CA", "VERIFY_IDENTITY"}:
            msg = f"unsupported ssl-mode: {mode}"
            raise ValueError(msg)

        context = create_default_context(cafile=parameters.get("ssl-ca"))
        # The certificates MySQL generates for itself fail the strict X.509 checks.
        context.verify_flags &= ~VERIFY_X509_STRICT
        context.check_hostname = mode == "VERIFY_IDENTITY"
        context.verify_mode = CERT_NONE if mode == "REQUIRED" else CERT_REQUIRED
        if "ssl-cert" in parameters:
            context.load_cert_chain(parameters["ssl-cert"], parameters.get("ssl-key"))
        return context, False

    @classmethod
    def _rollback(cls, connection: Connection[Cursor]) -> None:
        """Roll back; a lost connection must not hide the error that lost it.

        Args:
            connection: pymysql.Connection[pymysql.cursors.Cursor] - The connection.

        """
        with suppress(MySQLError):
            connection.rollback()

    @classmethod
    def _collect_resultset(
        cls,
        connection: Connection[Cursor],
        sql: str,
        limits: Limits,
    ) -> ResultSet:
        try:
            with connection.cursor(SSCursor) as cursor:
                cls._begin(cursor, limits)
                return cls._fetch_resultset(cursor, sql, Collector(limits))
        except MySQLError as error:
            raise QueryError(*cls._classify_error(error)) from error
        finally:
            cls._rollback(connection)

    @classmethod
    def _explain(
        cls,
        connection: Connection[Cursor],
        sql: str,
        limits: Limits,
    ) -> float | None:
        """Read the cost of the query's plan inside the same guards as a run.

        Args:
            connection: pymysql.Connection[pymysql.cursors.Cursor] - The connection.
            sql: str - SQL regenerated by the firewall.
            limits: Limits - Bounds.

        Returns:
            float | None - The plan's cost; None if the plan carries none.

        Raises:
            QueryError: If the database refuses or fails the query.

        """
        try:
            with connection.cursor() as cursor:
                cls._begin(cursor, limits)
                plan = cls._rows(cursor, f"EXPLAIN FORMAT=JSON {sql}")[0][0]
        except MySQLError as error:
            raise QueryError(*cls._classify_error(error)) from error
        finally:
            cls._rollback(connection)
        return plan_cost(json.loads(str(plan)))  # pyright: ignore[reportAny]

    @classmethod
    def _begin(cls, cursor: Cursor, limits: Limits) -> None:
        """Make the session read-only, bound its statements, open a transaction.

        Args:
            cursor: pymysql.cursors.Cursor - The cursor.
            limits: Limits - Bounds.

        """
        _ = cursor.execute(_READ_ONLY)
        _ = cursor.execute(
            "SET SESSION max_execution_time = %s",
            (limits.statement_timeout_ms,),
        )
        _ = cursor.execute("START TRANSACTION READ ONLY")

    @classmethod
    def _fetch_resultset(
        cls,
        cursor: SSCursor,
        sql: str,
        collector: Collector,
    ) -> ResultSet:
        """Fetch a result set from the cursor.

        Args:
            cursor: pymysql.cursors.SSCursor - The cursor.
            sql: str - The SQL to execute.
            collector: Collector - The collector.

        Returns:
            ResultSet - The result set.

        """
        _ = cursor.execute(sql)
        columns = [str(item[0]) for item in cursor.description or ()]
        while rows := cast("tuple[Row]", cursor.fetchmany(_FETCHMANY_LIMIT)):
            if not all(collector.add(row) for row in rows):
                break
        return collector.result(columns)

    @classmethod
    def _classify_error(cls, error: MySQLError) -> tuple[ErrorClass, str]:
        first = cast("object", error.args[0]) if error.args else 0
        code = first if isinstance(first, int) else 0
        text = str(error)
        if isinstance(error, InterfaceError):
            return ErrorClass.CONNECTION, text
        for codes, error_class in (
            (_TIMEOUT, ErrorClass.TIMEOUT),
            (_PERMISSION, ErrorClass.PERMISSION_DENIED),
            (_READ_ONLY_ERRORS, ErrorClass.READ_ONLY),
            (_INVALID, ErrorClass.INVALID_QUERY),
            (_CONNECTION, ErrorClass.CONNECTION),
        ):
            if code in codes:
                return error_class, text
        return ErrorClass.DATABASE, text
