from __future__ import annotations

import asyncio
from asyncio import Lock, to_thread
from typing import TYPE_CHECKING, Self, cast, override
from urllib.parse import unquote, urlsplit

from pymysql import connect as pymysql_connect
from pymysql.cursors import SSCursor
from pymysql.err import MySQLError

from forbql.engines import (
    Collector,
    ErrorClass,
    QueryEngine,
    QueryError,
    Restriction,
    ResultSet,
)
from forbql.firewall import SchemaSnapshot
from forbql.policy import Engine, Limits

if TYPE_CHECKING:
    from pymysql.connections import Connection
    from pymysql.cursors import Cursor

_FETCHMANY_LIMIT = 200
"""Prefetch limit for MySQL."""


_SQL_MODE = (
    "ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,"
    "ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
)
"""SQL mode for MySQL.


sqlglot's MySQL dialect reads '...' as strings and `...` as identifiers, with
backslash escapes: the session must agree, or checked SQL means something else.
"""

_READ_ONLY = "SET SESSION transaction_read_only = ON"
"""SQL to set the session to read-only.

A read-only transaction alone does not stop DDL: MySQL commits before DDL, ending
the transaction. The session-wide read-only mode refuses DDL too.
"""


_SNAPSHOT = """
SELECT table_schema, table_name, column_name
FROM information_schema.columns
WHERE table_schema = DATABASE()
ORDER BY table_name, ordinal_position
"""
"""SQL to get the schema snapshot for MySQL."""


_TIMEOUT = {1028, 1317, 3024}
"""Error codes for timeouts."""

_PERMISSION = {1044, 1045, 1142, 1143, 1227}
"""Error codes for permissions."""

_READ_ONLY_ERRORS = {1290, 1792}
"""Error codes for read-only errors."""

_INVALID = {1054, 1064, 1146, 1305, 1582}
"""Error codes for invalid errors."""

_CONNECTION = {2003, 2006, 2013}
"""Error codes for MySQL."""


type Row = tuple[object, ...]
"""A row of data from MySQL."""


class MySQLEngine(QueryEngine):
    """A connection in session read-only mode whose every query is rolled back.

    Args:
        connection: pymysql.Connection - Opened by `connect`.

    """

    _connection: Connection
    _lock: Lock
    """
    A lock to serialize access to the connection.
    One connection, used from worker threads one call at a time.
    """

    def __init__(self, connection: Connection) -> None:
        self._connection = connection
        self._lock = Lock()

    @classmethod
    async def connect(cls, dsn: str) -> Self:
        """Open a connection with the sql_mode the firewall assumes.

        Args:
            dsn: str - `mysql://user:password@host:port/database`.

        Returns:
            Self - The engine.

        """
        return cls(await asyncio.to_thread(cls._open_connection, dsn))

    @classmethod
    def _open_connection(cls, dsn: str) -> Connection[Cursor]:
        """Open a connection with the sql_mode the firewall assumes.

        Args:
            dsn: str - `mysql://user:password@host:port/database`.

        Returns:
            pymysql.Connection[pymysql.cursors.Cursor] - The connection.

        Raises:
            QueryError: If the connection fails.

        """
        url = urlsplit(dsn)
        try:
            return pymysql_connect(
                host=url.hostname or "127.0.0.1",
                port=url.port or 3306,
                user=unquote(url.username or ""),
                password=unquote(url.password or ""),
                database=url.path.lstrip("/") or None,
                charset="utf8mb4",
                autocommit=False,
                init_command=f"SET SESSION sql_mode = '{_SQL_MODE}'",
            )
        except MySQLError as error:
            raise QueryError(ErrorClass.CONNECTION, str(error)) from error

    @override
    async def execute(self, sql: str, limits: Limits) -> ResultSet:
        """Run one query in a read-only transaction and roll it back.

        Args:
            sql: Query regenerated by Firewall.
            limits: Limits - Time, row ans byte bounds.

        Returns:
            ResultSet - The capped rows.

        """
        async with self._lock:
            return await to_thread(
                self._collect_resultset,
                self._connection,
                sql,
                limits,
            )

    @override
    async def restrict(self, restriction: Restriction, /) -> None:
        """Nothing to do: the account's grants enforce what it may read."""

    @override
    async def close(self) -> None:
        """Close the connection."""
        async with self._lock:
            return await to_thread(self._connection.close)

    @property
    @override
    def engine(self) -> Engine:
        """The engine of the connection."""
        return Engine.MYSQL

    @classmethod
    def _fetch_tables(
        cls,
        connection: Connection[Cursor],
    ) -> tuple[list[Row], str]:
        """Fetch the tables of the current database.

        Args:
            connection: pymysql.Connection[pymysql.cursors.Cursor] - The connection.

        Returns:
            tuple[list[Row], str] - The tables and the current database.
        """
        with connection.cursor() as cursor:
            _ = cursor.execute(_SNAPSHOT)
            rows = cast("list[Row]", list(cursor.fetchall()))
            _ = cursor.execute("SELECT DATABASE()")
            database = cast("tuple[object, ...]", cursor.fetchone())[0]
        connection.rollback()
        return rows, str(database)

    @classmethod
    def _collect_resultset(
        cls,
        connection: Connection[Cursor],
        sql: str,
        limits: Limits,
    ) -> ResultSet:
        try:
            with connection.cursor(SSCursor) as cursor:
                _ = cursor.execute(_READ_ONLY)
                _ = cursor.execute(
                    "SET SESSION max_execution_time = %s",
                    (limits.statement_timeout_ms,),
                )
                _ = cursor.execute("START TRANSACTION READ ONLY")
                return cls._fetch_resultset(cursor, sql, Collector(limits))
        except MySQLError as error:
            raise QueryError(*cls._classify_error(error)) from error
        finally:
            connection.rollback()

    @override
    async def snapshot(self) -> SchemaSnapshot:
        """Read the columns of the current database the account may use.

        Returns:
            SchemaSnapshot - The schema; the default schema is the current database.

        """
        async with self._lock:
            rows, default_schema = await to_thread(self._fetch_tables, self._connection)

        tables: dict[str, list[str]] = {}
        for schema, table, col in rows:
            tables.setdefault(f"{schema}.{table}", []).append(str(col))

        return SchemaSnapshot(
            default_schema=default_schema,
            tables={key: tuple(names) for key, names in tables.items()},
        )

    @classmethod
    def _fetch_resultset(
        cls,
        cursor: SSCursor,
        sql: str,
        collector: Collector,
    ) -> ResultSet:
        """Fetch a result set from the cursor.

        Args:
            cursor: pymysql.cursors.SSCursor - The cursor.
            sql: str - The SQL to execute.
            collector: Collector - The collector.

        Returns:
            ResultSet - The result set.

        """
        _ = cursor.execute(sql)
        columns = [str(item[0]) for item in cursor.description or ()]
        while rows := cast("tuple[Row]", cursor.fetchmany(_FETCHMANY_LIMIT)):
            if not all(collector.add(row) for row in rows):
                break
        return collector.result(columns)

    @classmethod
    def _classify_error(cls, error: MySQLError) -> tuple[ErrorClass, str]:
        first = cast("object", error.args[0]) if error.args else 0
        code = first if isinstance(first, int) else 0
        text = str(error)
        for codes, error_class in (
            (_TIMEOUT, ErrorClass.TIMEOUT),
            (_PERMISSION, ErrorClass.PERMISSION_DENIED),
            (_READ_ONLY_ERRORS, ErrorClass.READ_ONLY),
            (_INVALID, ErrorClass.INVALID_QUERY),
            (_CONNECTION, ErrorClass.CONNECTION),
        ):
            if code in codes:
                return error_class, text
        return ErrorClass.DATABASE, text
