"""What every engine offers the session."""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from collections.abc import Mapping

    from forbql.firewall import SchemaSnapshot
    from forbql.policy import Engine, Limits

    from ._privileges import PrivilegeReport
    from ._result import ResultSet


@dataclass(frozen=True, slots=True)
class Restriction:
    """What a profile may touch, for engines that enforce it themselves.

    Attributes:
        allow_recursive: bool - Whether recursive CTEs may run.
        functions: frozenset[str] - Extra function names the profile allows.
        tables: Mapping[str, tuple[str, ...]] - Visible columns per `schema.table`.

    """

    allow_recursive: bool
    functions: frozenset[str]
    tables: Mapping[str, tuple[str, ...]]


class QueryEngine(ABC):
    """A read-only connection to one user database."""

    @property
    @abstractmethod
    def engine(self) -> Engine:
        """The engine that this session runs on."""

    @abstractmethod
    async def snapshot(self) -> SchemaSnapshot:
        """Read the tables and columns the connection's role can see.

        Returns:
            SchemaSnapshot - The schema.

        """

    @abstractmethod
    async def check_privileges(self) -> PrivilegeReport:
        """Find what the connection may do beyond reading.

        Returns:
            PrivilegeReport - Rights that stop forbql from starting, and rights worth
                revoking.

        """

    @abstractmethod
    async def restrict(self, restriction: Restriction, /) -> None:
        """Limit the connection to the profile's tables, columns and functions.

        Engines with roles leave this to the database role; SQLite has none and
        installs an authorizer.

        Args:
            restriction: Restriction - What the profile may touch.

        """

    @abstractmethod
    async def execute(self, sql: str, limits: Limits) -> ResultSet:
        """Run one checked query in a read-only transaction that is rolled back.

        Args:
            sql: str - SQL regenerated by the firewall.
            limits: Limits - Time, row and byte bounds.

        Returns:
            ResultSet - The capped rows.

        """

    @abstractmethod
    async def close(self) -> None:
        """Close the connection.

        The engine may need to clean up the connection, such as closing a cursor.

        """
        ...
