from __future__ import annotations

from asyncio import Lock, to_thread
from pathlib import Path
from sqlite3 import SQLITE_LIMIT_LENGTH, Connection, Cursor, Error, OperationalError
from sqlite3 import connect as sqlite_connect
from time import monotonic
from typing import Self, cast, override

# The engine's building blocks come from their own modules, not from the package:
# forbql.engines imports this subpackage through connect(), which would be a cycle.
from forbql.engines._errors import ErrorClass, QueryError
from forbql.engines._protocol import QueryEngine, Restriction
from forbql.engines._result import Collector, ResultSet
from forbql.firewall import SchemaSnapshot
from forbql.policy import Engine, Limits

from ._authorizer import authorizer

_PREFETCH_LIMIT = 200
_PROGRESS_STEPS = 10_000

_TABLES = """
SELECT name FROM sqlite_schema
WHERE type IN ('table', 'view') AND name NOT LIKE 'sqlite_%'
ORDER BY name
"""


_COLUMNS = "SELECT name FROM pragma_table_info(?) ORDER BY cid"


class SQLiteEngine(QueryEngine):
    """A read-only SQLite file behind an authorizer.

    Args:
        connection: sqlite3.Connection - Opened read-only by `connect`.

    """

    _connection: Connection
    _lock: Lock
    _stored: frozenset[str]

    def __init__(self, connection: Connection) -> None:
        self._connection = connection
        self._lock = Lock()
        self._stored = frozenset()

    @property
    @override
    def engine(self) -> Engine:
        """Which engine this is."""
        return Engine.SQLITE

    @classmethod
    async def connect(cls, dsn: str) -> Self:
        """Open a database file read-only.

        Args:
            dsn: str - Path to the file, optionally prefixed with `sqlite:///`.

        Returns:
            Self - The engine.

        """
        return cls(
            await to_thread(cls._open_connection, Path(dsn.removeprefix("sqlite:///"))),
        )

    @override
    async def execute(self, sql: str, limits: Limits) -> ResultSet:
        """Run one query with a deadline and the profile's caps.

        Args:
            sql: str - SQL regenerated by the firewall.
            limits: Limits - Time, row and byte bounds.

        Returns:
            ResultSet - The capped rows.

        """
        async with self._lock:
            return await to_thread(
                self._collect_resultset,
                self._connection,
                sql,
                limits,
            )

    @override
    async def snapshot(self) -> SchemaSnapshot:
        """Read tables and views and their columns.

        Returns:
            SchemaSnapshot - The schema, in the `main` schema.

        """
        async with self._lock:
            tables = await to_thread(self._fetch_tables, self._connection)
        self._stored = frozenset(key.split(".", 1)[1] for key in tables)
        return SchemaSnapshot(default_schema="main", tables=tables)

    @override
    async def restrict(self, restriction: Restriction, /) -> None:
        """Install the authorizer: only visible columns and allowed functions.

        Args:
            restriction: Restriction - What the profile may touch.

        """
        check = authorizer(restriction, self._stored)
        async with self._lock:
            await to_thread(self._connection.set_authorizer, check)

    @override
    async def close(self) -> None:
        """Close the connection."""
        async with self._lock:
            return await to_thread(self._connection.close)

    @classmethod
    def _open_connection(cls, path: Path) -> Connection:
        if not path.is_file():
            raise QueryError(ErrorClass.CONNECTION, f"no database file at {path}")
        connection = sqlite_connect(
            f"file:{path}?mode=ro",
            uri=True,
            check_same_thread=False,
            isolation_level=None,
        )
        _ = connection.execute("PRAGMA query_only = ON")
        _ = connection.execute("PRAGMA trusted_schema = OFF")
        if hasattr(connection, "enable_load_extension"):
            connection.enable_load_extension(False)  # ruff: ignore[boolean-positional-value-in-call]
        return connection

    @classmethod
    def _fetch_tables(cls, connection: Connection) -> dict[str, tuple[str, ...]]:
        """Fetch tables from DB.

        Args:
            connection: Opened connection to execute fetch tables query.

        Returns:
            dict[str, tuple[str, ...]] - tables with {name:columns}

        """
        names = cast("list[tuple[str]]", connection.execute(_TABLES).fetchall())
        tables: dict[str, tuple[str, ...]] = {}
        for (name,) in names:
            cursor = connection.execute(_COLUMNS, (name,))
            cols = cast("list[tuple[str]]", cursor.fetchall())
            tables[f"main.{name}"] = tuple(c for (c,) in cols)
        return tables

    @classmethod
    def _fetch_resultset(cls, cursor: Cursor, collector: Collector) -> ResultSet:
        cols = [str(item[0]) for item in cursor.description or ()]
        try:
            while rows := cast(
                "list[tuple[object, ...]]",
                cursor.fetchmany(_PREFETCH_LIMIT),
            ):
                if not all(collector.add(row) for row in rows):
                    break
        finally:
            cursor.close()
        return collector.result(cols)

    @classmethod
    def _collect_resultset(
        cls,
        connection: Connection,
        sql: str,
        limits: Limits,
    ) -> ResultSet:
        deadline = monotonic() + limits.statement_timeout_ms / 1000
        connection.set_progress_handler(
            lambda: int(monotonic() > deadline),
            _PROGRESS_STEPS,
        )
        _ = connection.setlimit(SQLITE_LIMIT_LENGTH, limits.max_result_bytes)
        try:
            return cls._fetch_resultset(connection.execute(sql), Collector(limits))
        except Error as error:
            raise QueryError(*cls._classify_error(error)) from error
        finally:
            connection.set_progress_handler(None, 0)

    @classmethod
    def _classify_error(cls, error: Error) -> tuple[ErrorClass, str]:
        text = str(error)
        if "interrupted" in text:
            return ErrorClass.TIMEOUT, text
        # Authorizer refusals: "not authorized" for statements, "prohibited" for reads.
        if "not authorized" in text or "prohibited" in text:
            return ErrorClass.PERMISSION_DENIED, text
        if "readonly" in text or "read-only" in text:
            return ErrorClass.READ_ONLY, text
        if isinstance(error, OperationalError):
            return ErrorClass.INVALID_QUERY, text
        return ErrorClass.DATABASE, text
