from __future__ import annotations

from asyncio import Lock, to_thread
from operator import itemgetter
from os import W_OK, access
from pathlib import Path
from sqlite3 import SQLITE_LIMIT_LENGTH, Connection, Cursor, Error, OperationalError
from sqlite3 import connect as sqlite_connect
from time import monotonic
from typing import Self, cast, override

from forbql.engines._describe import Relation, assemble

# The engine's building blocks come from their own modules, not from the package:
# forbql.engines imports this subpackage through connect(), which would be a cycle.
from forbql.engines._errors import ErrorClass, QueryError
from forbql.engines._privileges import PrivilegeReport
from forbql.engines._protocol import QueryEngine, Restriction
from forbql.engines._result import Collector, ResultSet
from forbql.engines._thread import run_locked
from forbql.firewall import ColumnInfo, ForeignKey, SchemaCatalog
from forbql.policy import Engine, Limits

from ._authorizer import authorizer

_PREFETCH_LIMIT = 200
_PROGRESS_STEPS = 10_000

_TABLES = """
SELECT name, type = 'view', sql FROM sqlite_schema
WHERE type IN ('table', 'view') AND name NOT LIKE 'sqlite_%'
ORDER BY name
"""

_COLUMNS = 'SELECT name, type, "notnull", pk FROM pragma_table_info(?) ORDER BY cid'

_KEYS = (
    'SELECT id, "table", "from", "to" FROM pragma_foreign_key_list(?) ORDER BY id, seq'
)


class SQLiteEngine(QueryEngine):
    """A read-only SQLite file behind an authorizer.

    Args:
        connection: sqlite3.Connection - Opened read-only by `connect`.
        path: Path - The database file.

    """

    _connection: Connection
    _path: Path
    _lock: Lock
    _stored: frozenset[str]

    def __init__(self, connection: Connection, path: Path) -> None:
        self._connection = connection
        self._path = path
        self._lock = Lock()
        self._stored = frozenset()

    @property
    @override
    def engine(self) -> Engine:
        """Which engine this is."""
        return Engine.SQLITE

    @classmethod
    async def connect(cls, dsn: str) -> Self:
        """Open a database file read-only.

        Args:
            dsn: str - Path to the file, optionally prefixed with `sqlite:///`.

        Returns:
            Self - The engine.

        """
        path = Path(dsn.removeprefix("sqlite:///"))
        return cls(await to_thread(cls._open_connection, path), path)

    @override
    async def execute(self, sql: str, limits: Limits) -> ResultSet:
        """Run one query with a deadline and the profile's caps.

        Args:
            sql: str - SQL regenerated by the firewall.
            limits: Limits - Time, row and byte bounds.

        Returns:
            ResultSet - The capped rows.

        """
        return await run_locked(
            self._lock,
            self._collect_resultset,
            self._connection,
            sql,
            limits,
        )

    @override
    async def describe(self) -> SchemaCatalog:
        """Read every table and view in the file, with keys; SQLite keeps no comments.

        Returns:
            SchemaCatalog - The catalog, in the `main` schema.

        """
        catalog = await run_locked(self._lock, self._fetch_catalog, self._connection)
        self._stored = frozenset(key.split(".", 1)[1] for key in catalog.tables)
        return catalog

    @override
    async def check_privileges(self) -> PrivilegeReport:
        """SQLite has no roles; warn when the process could write the file itself.

        Returns:
            PrivilegeReport - A warning when the file is writable, nothing else.

        """
        if not access(self._path, W_OK):
            return PrivilegeReport()
        warning = (
            f"the process may write {self._path}; forbql opens it read-only, "
            f"but a read-only file is safer: chmod a-w {self._path}"
        )
        return PrivilegeReport(warnings=(warning,))

    @override
    async def restrict(self, restriction: Restriction, /) -> None:
        """Install the authorizer: only visible columns and allowed functions.

        Args:
            restriction: Restriction - What the profile may touch.

        """
        check = authorizer(restriction, self._stored)
        await run_locked(self._lock, self._connection.set_authorizer, check)

    @override
    async def estimate(self, sql: str, limits: Limits) -> None:
        """SQLite's planner reports no cost, so there is nothing to compare.

        Args:
            sql: str - SQL regenerated by the firewall.
            limits: Limits - Bounds.

        """

    @override
    async def close(self) -> None:
        """Close the connection."""
        await run_locked(self._lock, self._connection.close)

    @classmethod
    def _open_connection(cls, path: Path) -> Connection:
        if not path.is_file():
            raise QueryError(ErrorClass.CONNECTION, f"no database file at {path}")
        connection = sqlite_connect(
            f"file:{path}?mode=ro",
            uri=True,
            check_same_thread=False,
            isolation_level=None,
        )
        _ = connection.execute("PRAGMA query_only = ON")
        _ = connection.execute("PRAGMA trusted_schema = OFF")
        if hasattr(connection, "enable_load_extension"):
            connection.enable_load_extension(False)  # ruff: ignore[boolean-positional-value-in-call]
        return connection

    @classmethod
    def _fetch_catalog(cls, connection: Connection) -> SchemaCatalog:
        """Read `sqlite_schema` and the table pragmas, and put the catalog together.

        Args:
            connection: sqlite3.Connection - The open file.

        Returns:
            SchemaCatalog - The catalog.

        Raises:
            QueryError: If the file is not a database or cannot be read.

        """
        found: dict[str, Relation] = {}
        references: list[tuple[str, int, str, str, str | None]] = []
        try:
            names = cast(
                "list[tuple[str, int, str]]",
                connection.execute(_TABLES).fetchall(),
            )
            for name, view, sql in names:
                relation = Relation(view=bool(view), definition=sql if view else None)
                found[f"main.{name}"] = relation
                cls._read_columns(connection, name, relation)
                references.extend(
                    (name, *row)
                    for row in cast(
                        "list[tuple[int, str, str, str | None]]",
                        connection.execute(_KEYS, (name,)).fetchall(),
                    )
                )
        except Error as error:
            raise QueryError(*cls._classify_error(error)) from error
        cls._add_keys(found, references)
        return assemble("main", found)

    @classmethod
    def _read_columns(
        cls,
        connection: Connection,
        name: str,
        relation: Relation,
    ) -> None:
        """Read a table's columns and primary key.

        Args:
            connection: sqlite3.Connection - The open file.
            name: str - Table name.
            relation: Relation - Where to put them.

        """
        rows = cast(
            "list[tuple[str, str, int, int]]",
            connection.execute(_COLUMNS, (name,)).fetchall(),
        )
        relation.columns.extend(
            # An INTEGER PRIMARY KEY is the rowid: never NULL, though not declared so.
            ColumnInfo(name=column, type=kind, nullable=not (notnull or pk))
            for column, kind, notnull, pk in rows
        )
        relation.primary_key = tuple(
            column for column, _, _, pk in sorted(rows, key=itemgetter(3)) if pk
        )

    @classmethod
    def _add_keys(
        cls,
        found: dict[str, Relation],
        references: list[tuple[str, int, str, str, str | None]],
    ) -> None:
        """Group foreign key rows, one per column, into keys.

        A reference that names no column means the target's primary key.

        Args:
            found: dict[str, Relation] - Relations by `main.table`.
            references: list[tuple[str, int, str, str, str | None]] - Table, key id,
                target, own column and target column, per row.

        """
        grouped: dict[tuple[str, int], list[tuple[str, str, str | None]]] = {}
        for table, key, target, own, theirs in references:
            grouped.setdefault((table, key), []).append((target, own, theirs))
        for (table, _), rows in grouped.items():
            target = f"main.{rows[0][0]}"
            named = tuple(theirs for _, _, theirs in rows if theirs is not None)
            implied = found[target].primary_key if target in found else ()
            found[f"main.{table}"].foreign_keys.append(
                ForeignKey(
                    columns=tuple(own for _, own, _ in rows),
                    table=target,
                    references=named if len(named) == len(rows) else implied,
                ),
            )

    @classmethod
    def _fetch_resultset(cls, cursor: Cursor, collector: Collector) -> ResultSet:
        cols = [str(item[0]) for item in cursor.description or ()]
        try:
            while rows := cast(
                "list[tuple[object, ...]]",
                cursor.fetchmany(_PREFETCH_LIMIT),
            ):
                if not all(collector.add(row) for row in rows):
                    break
        finally:
            cursor.close()
        return collector.result(cols)

    @classmethod
    def _collect_resultset(
        cls,
        connection: Connection,
        sql: str,
        limits: Limits,
    ) -> ResultSet:
        deadline = monotonic() + limits.statement_timeout_ms / 1000
        connection.set_progress_handler(
            lambda: int(monotonic() > deadline),
            _PROGRESS_STEPS,
        )
        _ = connection.setlimit(SQLITE_LIMIT_LENGTH, limits.max_result_bytes)
        try:
            return cls._fetch_resultset(connection.execute(sql), Collector(limits))
        except Error as error:
            raise QueryError(*cls._classify_error(error)) from error
        finally:
            connection.set_progress_handler(None, 0)

    @classmethod
    def _classify_error(cls, error: Error) -> tuple[ErrorClass, str]:
        text = str(error)
        if "interrupted" in text:
            return ErrorClass.TIMEOUT, text
        # Authorizer refusals: "not authorized" for statements, "prohibited" for reads.
        if "not authorized" in text or "prohibited" in text:
            return ErrorClass.PERMISSION_DENIED, text
        if "readonly" in text or "read-only" in text:
            return ErrorClass.READ_ONLY, text
        if isinstance(error, OperationalError):
            return ErrorClass.INVALID_QUERY, text
        return ErrorClass.DATABASE, text
